### ISSUE TITLE
Empty string variable not recognized as variable during transformation

### ISSUE THREAD

**Issue by mfidemraizer** [MathiasPaumgarten/grunt-json-bake#7]
I've found that providing a variable holding an empty string will result in a warning like this:

> No variable definition found for: gitBranchPrefix

Where `gitBranchPrefix` is the whole variable configured as follows:

```
   development: {
                files: {
                    "./app/js/config/app.config.json": "./app/js/config/_app.config.json"
                },
                options: {
                    variables: {
                        target: "development",
                        gitBranchPrefix: gitBranchPrefix
                    }
                }
            }
```

It would be interesting to support this scenario, because sometimes you want to use some variable and, depending on the use case, maybe you want it to print an empty string. 

Actually, it works as expected. The issue is the warning :)

**Comment by MathiasPaumgarten** [comment]
Hey there,

That is a good point. the way I check for the variable to exist is not safe for empty strings ([line 168](https://github.com/MathiasPaumgarten/grunt-json-bake/blob/master/tasks/json_bake.js#L168)). 

I will update that. Thanks.

**Comment by mfidemraizer** [comment]
Thank you ;)
